### ISSUE TITLE
sendFile not working with video files

### ISSUE THREAD

**Issue by robertsLando** [danielcardeenas/sulla#243]
I'm tring to send an mp4 file without success. The api doesn't return any error, ideas? @danielcardeenas 

Error thrown: 

```
Uncaught (in promise) Error: InvalidMediaFileType: ExtendableError
    at t.value [as sendToChat]
```

**Comment by danielcardeenas** [comment]
Con you send me the video file?

**Comment by robertsLando** [comment]
@danielcardeenas I have added a test

**Comment by robertsLando** [comment]
The strange thing is that I successfully can send that file using whatsapp web on my pc, but not with sulla. Even If I set headless to false and I try to send the file from there I'm get the error shown before. Maybe puppeteeer needs an update?

**Comment by danielcardeenas** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/2654812/78921769-0a33c900-7a5b-11ea-92d6-a30095606226.png)

I just messed up with the useChrome flag, now its using Chromium as default

**Comment by robertsLando** [comment]
Perfect! I suggest to keep tests so we can quick test things if get broken

——————

Daniel - Software Engineer

Support me at:
    Github sponsors

**Comment by danielcardeenas** [comment]
Yeah I will write some tests for his kind of issues

**Comment by danielcardeenas** [comment]
Bump to new version `2.3.6`

**Comment by robertsLando** [comment]
You forgot to use “npm run release” fot the release

——————

Daniel - Software Engineer

Support me at:
    Github sponsors

**Comment by robertsLando** [comment]
@danielcardeenas Videos files are now sent as files and they cannot be played directly

**Comment by danielcardeenas** [comment]
Can you show me your code?
It is currently working as expected:
![20200410_093653](https://user-images.githubusercontent.com/2654812/78998743-dca85780-7b0e-11ea-86ff-f08b517e6057.jpg)

**Comment by robertsLando** [comment]
Now it's working. Dunno why :confused: Seems that if useChrome is false it throws that error I mentioned above, any ideas?

**Comment by danielcardeenas** [comment]
In order to send videos, you need to use a chrome instance. Chromium does not support that feature
